(require "vm.lisp")
(defun run ()
    (progn
    (make-vm)
    (vm-load 'vm '(
        (MOVE 5 :R1)  
        (JMP label1)  
        (MOVE 3 :R2)  
        (JLE label2)  
        (JEQ label8)  
        (LABEL label8) 
        (LABEL label1)  
        (NOP)  
        (LABEL label2)  
        (NOP) 
        (JMP label3)
        (ADD 5 :R1)
        )  
)
    (vm-exec 'vm)
    (vm-print)
    )
)

